// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:44f00850-83b7-42ce-96e1-e7fdc6370be5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_JgufZvswK",
    "aws_user_pools_web_client_id": "6af0000t4unth4gv57ugk5bidc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x5zjp4ikmbd2dpxkh5hygxwreu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;