// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dcf4d6bd-6b9d-47e3-8973-fcb4170c5c99",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5XjIHe0gK",
    "aws_user_pools_web_client_id": "6ej4khufqb66slg7vjhf6e51ep",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6thq67jmavhi7mitvpushultdu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "priest-app-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d2jiwlxdwwkz34.cloudfront.net"
};

export default awsmobile;